version: "3.6"
services:
  web:
    image: ranckosolutionsinc/todo-django-api:latest
    container_name: todo-django-api
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    depends_on:
      - database
  database:
    image: mongo
    container_name: todo-django-api_database
    #ports:
    #  - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    volumes:
      - mongo-db:/data/db
  mongo_compass:
    image: mongo-express
    container_name: todo-django-api_database_ui
    restart: always
    ports:
      - 8090:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=database
    depends_on:
      - database
volumes:
  mongo-db:
